# Generated by Django 5.2.8 on 2025-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='languages',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('RU', 'Russian'), ('AR', 'Arabic'), ('HI', 'Hindi'), ('PT', 'Portuguese'), ('other', 'Other')], default='other', max_length=2000),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')]),
        ),
    ]
