# Generated by Django 5.2.8 on 2025-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_languages_alter_company_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='languages',
            field=models.CharField(choices=[('arabic', 'Arabic'), ('english', 'English'), ('korean', 'Korean'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('other', 'Other')], max_length=50),
        ),
    ]
