# Generated by Django 5.2.8 on 2025-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='final_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
