# Generated by Django 5.2.8 on 2025-12-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_language_companyreview_alter_company_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='languages',
        ),
        migrations.AddField(
            model_name='company',
            name='languages',
            field=models.ManyToManyField(to='companies.language'),
        ),
    ]
