# Generated by Django 5.2.8 on 2025-12-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_rename_language_name_language_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=100)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='company',
            name='file',
        ),
        migrations.RemoveField(
            model_name='company',
            name='final_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='languages',
            field=models.ManyToManyField(blank=True, to='companies.language'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.country'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.country'),
        ),
        migrations.DeleteModel(
            name='CompanyReview',
        ),
    ]
