# Generated by Django 5.2.8 on 2025-12-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_city_country_remove_company_cost_remove_company_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
