# Generated by Django 5.2.8 on 2025-12-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0011_alter_country_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('instant', 'Instant Translation'), ('hire', 'Hire a Translator')], max_length=20)),
                ('specialty', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('duration_days', models.IntegerField()),
                ('translator_name', models.CharField(max_length=100)),
                ('translator_specialty', models.CharField(max_length=100)),
                ('translator_start_date', models.DateField()),
                ('translator_duration_days', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.language')),
            ],
        ),
    ]
