# Generated by Django 5.2.8 on 2025-12-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_country_flag'),
        ('translation_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='duration_days',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.language'),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='translator_duration_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='translator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='translator_specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='translator_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
