# Generated by Django 5.2.8 on 2025-12-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_request', '0002_alter_translationrequest_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
