# Generated by Django 5.2.8 on 2025-12-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_country_flag'),
        ('translation_request', '0003_translationrequest_cost_translationrequest_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='translator_language',
            field=models.ManyToManyField(blank=True, related_name='translator_languages', to='companies.language'),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='duration_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
