# Generated by Django 5.2.8 on 2025-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_request', '0004_translationrequest_translator_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationrequest',
            name='company',
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='company_name',
            field=models.CharField(default='Default Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='company_type',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private')], default='Default Name', max_length=20),
            preserve_default=False,
        ),
    ]
