# Generated by Django 5.2.8 on 2025-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_request', '0007_alter_translationrequest_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationrequest',
            name='translator_duration_days',
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='translator_language',
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='translator_name',
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='translator_specialty',
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='translator_start_date',
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
