# Generated by Django 5.2.8 on 2025-12-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('translation_request', '0009_translationrequest_company_translationrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='translation_request.translationrequest'),
        ),
    ]
