# Generated by Django 5.2.8 on 2025-12-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_company_name_profile_company_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatars/default.png', upload_to='images/avatars'),
        ),
    ]
