# Generated by Django 5.2.7 on 2025-12-01 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='country',
        ),
        migrations.AddField(
            model_name='translator',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='translators.city'),
            preserve_default=False,
        ),
    ]
