# Generated by Django 5.2.8 on 2025-12-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0002_remove_translator_country_translator_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translators.city'),
        ),
    ]
