# Generated by Django 5.2.7 on 2025-12-02 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0002_remove_translator_country_translator_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='translator',
            name='language',
        ),
        migrations.AlterField(
            model_name='translator',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translators.city'),
        ),
        migrations.AddField(
            model_name='translator',
            name='languages',
            field=models.ManyToManyField(to='translators.language'),
        ),
    ]
