# Generated by Django 5.2.7 on 2025-12-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0003_alter_translator_city'),
        ('translators', '0005_alter_review_user_alter_translator_user'),
    ]

    operations = [
    ]
