# Generated by Django 5.2.7 on 2025-12-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0006_merge_20251202_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1),
        ),
    ]
