# Generated by Django 5.2.7 on 2025-12-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0007_alter_translator_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='user',
        ),
    ]
