# Generated by Django 5.2.7 on 2025-12-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0010_alter_translator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
