# Generated by Django 5.2.7 on 2025-12-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0011_translator_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='translator',
            name='specialty',
        ),
        migrations.AddField(
            model_name='translator',
            name='specialties',
            field=models.ManyToManyField(to='translators.specialty'),
        ),
    ]
