# Generated by Django 5.2.7 on 2025-12-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Contact',
        ),
    ]
